/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as companies from "../companies.js";
import type * as edges from "../edges.js";
import type * as files from "../files.js";
import type * as folders from "../folders.js";
import type * as http from "../http.js";
import type * as invites from "../invites.js";
import type * as nodes from "../nodes.js";
import type * as orgStructureUsers from "../orgStructureUsers.js";
import type * as stripe from "../stripe.js";
import type * as structures from "../structures.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  companies: typeof companies;
  edges: typeof edges;
  files: typeof files;
  folders: typeof folders;
  http: typeof http;
  invites: typeof invites;
  nodes: typeof nodes;
  orgStructureUsers: typeof orgStructureUsers;
  stripe: typeof stripe;
  structures: typeof structures;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
