import { Inter } from "next/font/google"
import NavBar from "~/app/_components/nav-bar"
import { Toaster } from "~/components/ui/sonner"
import { cn } from "~/lib/utils"

import "~/styles/globals.css"
import SentryFeedbackWidget from "../lib/sentry-feedback"
import { ConvexClientProvider } from "./ConvexClientProvider"
import PostHogPageView from "./_analytics/PostHogPageView"
import { PHProvider } from "./_analytics/provider"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Struxts",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/waypoints.png" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "relative flex h-screen flex-col bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <ConvexClientProvider>
          <PHProvider>
            <NavBar />
            <main className="min-h-0 grow overflow-auto">
              <PostHogPageView />
              {children}
            </main>
            <Toaster theme="light" className="bg-card" />
          </PHProvider>
        </ConvexClientProvider>
        <SentryFeedbackWidget />
      </body>
    </html>
  )
}
