import "~/styles/globals.css"
import { Inter } from "next/font/google"

import { cn } from "~/lib/utils"

import { TRPCReactProvider } from "~/trpc/react"
import { ClerkProvider } from "@clerk/nextjs"
import NavBar from "~/app/_components/nav-bar"
import { Toaster } from "~/components/ui/sonner"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Struxts",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider signInFallbackRedirectUrl="/">
      <html lang="en">
        <body
          className={cn(
            "relative flex h-screen flex-col bg-background font-sans antialiased",
            inter.variable,
          )}
        >
          <TRPCReactProvider>
            <NavBar />
            <main className="min-h-0 grow overflow-auto">{children}</main>
          </TRPCReactProvider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}
